config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  post  '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get  '/carshare', to: 'static_pages#carshare'
  # カレンダーで管理する予約情報ルーティング
  get '/rlist',   to: 'events#rlist'
  get '/rmanage',   to: 'events#rmanage'
  resources :users
  resources :cars, only: [:show, :new, :edit, :create, :update, :destroy]
  resources :events
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 50 }
  validates :body, presence: true, length: { maximum: 1000 }
  validates :carmodel, presence: true
  validates :carsize, presence: true
  validates :other, presence: true
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
    before_action :logged_in_user, only: [:new, :create, :destroy]
    before_action :correct_user,   only: :destroy
  
    def create
      @car = current_user.car.build(car_params)
      if @car.save
        flash[:success] = "Car created!"
        redirect_to current_user
      else
        @feed_items = []
        render 'static_pages/home'
      end
    end
  
    def destroy
      @car.destroy
      flash[:success] = "Car deleted"
      redirect_to request.referrer || root_url
    end

    def show
      @car = Car.find(params[:id])
      set_car_id(@car.id)
    end

    def new
      @car = Car.new
    end

    def edit
      @car = Car.find(params[:id])
    end

    def update
      @car = Car.find(params[:id])
      if @car.update_attributes(car_params)
        flash[:success] = "CarShare updated"
        redirect_to @car
      else
        render 'edit'
      end
    end

    def destroy
      @user = @car.user
      @car.destroy
      flash[:success] = "Car deleted"
      redirect_to redirect_before_url
    end
  
    private
  
      def car_params
        params.require(:car).permit(:title, :body, :carmodel, :carsize, :other, :picture)
      end

      # 削除対象の記事を保有しているかの確認
      def correct_user
        @car = current_user.car.find_by(id: params[:id])
        redirect_to root_url if @car.nil?
      end
  end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_car.html.erb
<li id="car-<%= car.id %>">

  <div class="car_top">
    <!-- タイトル -->
    <span class="car_title"><%= car.title %></span>
    <!-- 車種 -->
    <span class="car_model"><%= car.carmodel %></span>
  </div>

  <!-- イメージ -->
 <%= image_tag car.picture.url if car.picture? %> 

  <!-- サイズ（定員など） -->
  <span class="car_size"><%= car.carsize %></span>

  <!-- 詳細情報ボタン -->
  <%= link_to "詳細を見る", car, class: "car_details_btn"%>

</li>

app/views/cars/_form.html.erb
<%= form_for(@car, url: yield(:url)) do |f| %>

    <%= render 'shared/error_messages', object: f.object %>

    <div>
      <%= f.label  "タイトル（車種名）" %>
      <%= f.text_field :title %>
    </div>

    <div>
      <%= f.label "詳細説明" %>
      <%= f.text_area :body %>
    </div>

    <div>
      <%= f.label "車両区分（電気自動車・ハイブリッド・ガソリン・ディーゼル）" %>
      <%= f.text_field :carmodel %>
    </div>

    <div>
      <%= f.label "車両サイズ（定員・ザイズ）" %>
      <%= f.text_field :carsize %>
    </div>

    <div>
      <%= f.label "備考" %>
      <%= f.text_area :other %>
    </div>

    <div class="picture">
      <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
    </div>

    <div>
      <%= image_tag @car.picture.url if @car.picture? %>
    </div>

    <%= f.submit yield(:button_text) %>

  <% end %>

app/views/cars/edit.html.erb
<% provide(:title, "Update CarShare") %>

<% provide(:url, car_path) %>
<% provide(:button_text, 'Update CarShare')%>

<div class="carshare-form">

  <h1>カーシェア情報 編集</h1>

  <%= render 'form' %>

</div>

app/views/cars/new.html.erb
<% provide(:title, "New CarShare") %>

<% provide(:url, cars_path) %>
<% provide(:button_text, 'Create CarShare')%>

<div class="carshare-form">

  <h1>カーシェア情報 新規登録</h1>

  <%= render 'form' %>

</div>

app/views/cars/show.html.erb
<!-- 投稿データ詳細画面 -->
<ul class="car-detail">

  <div class="detail_top">
    <!--戻るボタン（ユーザープロフィール画面へ戻る）-->
    <%= link_to "戻 る", redirect_before_url, class: "detail_btn" %>
    <!--修正ボタン-->
    <%= link_to "編 集", edit_car_path(@car), class: "detail_btn" %>
    <!--予約ボタン-->
    <% if logged_in? %>
      <%= link_to "予約する", contact_path, class: "detail_btn" %>
    <% end %>
    <!--削除ボタン-->
    <%= link_to "削 除", @car, method: :delete, data: { confirm: "You sure?" }, class: "detail_btn" %>
  </div>

  <div class="detail_title"><%= @car.title %></div>

  <div class="row detail-main">
    <div class="col-md-4">
      <!-- イメージ -->
      <%= image_tag @car.picture.url if @car.picture? %>
    </div>
    <div class="col-md-8">
      <div class="detail_model"><%= @car.carmodel %></div>
      <div class="detail_body"><%= @car.body %></div>
    </div>
  </div>

  <div class="detail_size"><%= @car.carsize %></div>

  <div class="detail_other"><%= @car.other %></div>

</ul>