config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  post  '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get  '/carshare', to: 'static_pages#carshare'
  # カレンダーで管理する予約情報ルーティング
  get '/rlist',   to: 'events#rlist'
  get '/rmanage',   to: 'events#rmanage'
  resources :users
  resources :cars, only: [:show, :new, :edit, :create, :update, :destroy]
  resources :events
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <ul>
    <li><%= link_to image_tag("twitter_icon.png", alt: "Twitter-Icon"), "#" %></li>
    <li><%= link_to image_tag("youtube_icon.png", alt: "Twitter-Icon"), "#" %></li>
  </ul>
  <p>@harrylabo 2019</p>
</footer>

app/views/layouts/_header.html.erb
<header style="z-index:1000;">

  <script>
    // ドロップダウンメニュー 
    $(function(){

      $("ul.sub").hide();

      // マウスオーバー時
      $("ul.menu li").hover(function(){
        // this -> 「ul.menu li ul」
        // not(:animated) -> アニメーション中のものに対しては処理しない
        $("ul.sub:not(:animated)", this).slideDown();

      // マウスリリース時
      }, function(){
        $("ul.sub",this).slideUp();
      });

    });
  </script>

  <!-- ヘッダー背景 -->
  <div class="nav-bg"></div>

  <!-- ロゴ -->
  <div class="logo" style="z-index:9999;">
    <%= link_to image_tag("logo.png", alt: "Logo"), root_path %>
  </div>

  <!-- ヘッダーナビゲーション -->
  <div id="nav-header">
    <nav>
      <ul class="menu">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "News",   help_path %></li>
        <li><%= link_to "About",   '#' %></li>
        <li><%= link_to "Works",   '#' %></li>
        <li><%= link_to "Contact",   contact_path %></li>

         <!-- ドロップダウンメニュー -->
        <% if logged_in? %>
          <!--  ユーザー一覧ページへのリンクを更新する<li><%= link_to "Users", users_path %></li> -->
          <li><%= current_user.name %>
            <ul class="sub">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li><%= link_to "Logout", logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "| LOG IN", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>

</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  
  <body>
    <%= render 'layouts/header' %>
    <div>
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>